#include "AngelScriptStubWriter.h"
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>

namespace licht::scripting
{
    AngelScriptStubWriter::AngelScriptStubWriter(std::filesystem::path outPath)
        : m_path(outPath)
    {
    }

    void AngelScriptStubWriter::clear_and_begin()
    {
        std::filesystem::create_directories(m_path.parent_path());
        m_ss.str({});
        m_ss.clear();

        m_ss << "// DO NOT MODIFY MANUALLY x Wanton.\n";
        m_ss << "// Generated by engine at runtime.\n\n";
    }

    void AngelScriptStubWriter::add_line(std::string_view stringView)
    {
        m_ss << stringView << "\n"; 
    }

    void AngelScriptStubWriter::flush()
    {
        std::ofstream f(m_path, std::ios::binary | std::ios::trunc);
        if (!f)
            throw std::runtime_error("Failed to open stub output file: " + m_path.string());

        const auto str = m_ss.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));
        f.flush();
    }

    const std::filesystem::path& AngelScriptStubWriter::path() const
    {
        return m_path;
    }
} // namespace licht::scripting